# 连接配置文件

["数据处理服务文档存储"]
# 注意，由于mongo存储日志，所以其在连接池中比较特殊
type = "mongo"
ip = "localhost"
port = 27017
user = ""
password = ""
mode = "logger"

["数据处理服务关系表存储-同步用"]
type = "pgsql"
ip = "localhost"
port = 5432
user = "postgres"
# password = "123456"
password = "Swq8855830."
mode = "sync_data"

["数据处理服务关系表存储-web用"]
type = "pgsql"
ip = "localhost"
port = 5432
user = "postgres"
# password = "123456"
password = "Swq8855830."
mode = "web_data"

["数据仓库中转数据库"]
type = "mysql"
ip = "10.24.5.32"
port = 3306
user = "cheakf"
password = "Swq8855830."
mode = "dataframe_flow_v2"

[EAS]
type = "oracle"
ip = "172.18.1.121"
port = 1521
user = "easselect"
password = "easselect"
mode = "eas"

[MES]
type = "oracle"
ip = "10.24.212.17"
port = 1521
user = "unimax_cg"
password = "unimax_cg"
mode = "ORCL"

[SHR]
type = "oracle"
ip = "10.24.204.67"
port = 1521
user = "shr_query"
password = "shr_queryZj123!"
mode = "ORCL"

["生产辅助系统"]
type = "sqlserver"
ip = "10.24.5.154"
port = 1433
user = "metro"
password = "Metro2023!"
mode = "城轨事业部"

["生产辅助系统-中转"]
type = "sqlserver"
ip = "10.24.5.154"
port = 1433
user = "metro"
password = "Metro2023!"
mode = "crrc_temp"

["金蝶云苍穹-测试库"]
type = "mysql"
ip = "10.24.204.37"
port = 3306
user = "kingdee"
password = "kingdee2020"
mode = "crrc_phm"

["金蝶云苍穹-正式库"]
type = "mysql"
ip = "10.24.206.138"
port = 3306
user = "cosmic"
password = "Mysql@2022!"
mode = "crrc_secd"

["机车数据库"]
type = "mysql"
ip = "10.29.31.159"
port = 3306
user = "crrc_temp"
password = "ETxkrRpCFDZ4LmMr"
mode = "crrc_temp"

["智能立库"]
type = "mysql"
ip = "10.24.5.21"
port = 3307
user = "root"
password = "jftxAdmin"
mode = "smart_warehouse"

["考勤系统"]
type = "sqlserver"
ip = "10.24.7.48"
port = 1433
user = "sa"
password = "Z@hc#8705!$"
mode = "GM_MT_70"