# 开启后不做socket通信
socket_debug = false
# socket通信的ip
socket_ip = "localhost"
# scoket通信的端口
socket_port = 10089
# 系统数据库同步速率上限定义，单位Mb/s
max_node_flow_cap = 1
# 任务轮询也就是数据同步的最小间隔，单位秒
min_sync_interval = 20
# 无任务时等待时间，单位秒
wait_sync_interval = 10
# 系统默认请求头，系统默认为1年，如若出现更新失败请更新请求头
[request_head]
Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
Accept-Encoding = "gzip, deflate"
Accept-Language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
Connection = "keep-alive"
Cookie = "locale=zh-cn; HEYFORM_BROWSER_ID=5kz0HHV08H35; HEYFORM_SESSION=yD%2BWeuNJqFCRYIGDkanMjxSbSNbZtEI2TXjJCA5QqwdTWhc7ZmJDkUN4eex04V2KBCZcKtSDRF6AC7cMeRhhu0ZPN0kC2dPZM6ptyqcpCrzJd8ggS7tdCMp..3N3rJgp; HEYFORM_LOGGED_IN=true"
DNT = "1"
Host = "18.0.163.64:10087"
Sec-Fetch-Dest = "document"
Sec-Fetch-Mode = "navigate"
Sec-Fetch-Site = "none"
Sec-Fetch-User = "?1"
Upgrade-Insecure-Requests = "1"
User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "Windows"
