# socket通信的ip
socket_ip = "localhost"
# scoket通信的端口
socket_port = 10089
# scoket接收的超时时间
socket_recv_timeout = 1
# 任务轮询也就是数据同步的最小间隔，单位秒
min_sync_interval = 20
# 无任务时等待时间，单位秒
wait_sync_interval = 10
# 节点两次同步变化的系数
node_sync_k = 20480
# 节点两次同步的最小间隔，该参数用在计算节点同步数据量的使用
node_sync_min = 600
# 节点两次同步的最大间隔，该参数用在计算节点同步数据量的使用
node_sync_max = 28800